In [1]:
import numpy as np
print("Imported successfully")

Imported successfully


In [2]:
numbers = np.array([1, 2, 3,  4, 5])
print(numbers)

[1 2 3 4 5]


In [3]:
print("Shape", numbers.shape)
print("Size", numbers.size)
print("Dimensions", numbers.ndim)
print("DataTypes", numbers.dtype)

Shape (5,)
Size 5
Dimensions 1
DataTypes int64


In [4]:
zeros = np.zeros((3,3))

ones = np.ones((2,4))

identity = np.eye(3)

print(zeros)
print(ones)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a = np.arange(1, 11)
b = np.arange(0, 21, 2)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [6]:
c = np.linspace(0, 10, 5)
print(c)

[ 0.   2.5  5.   7.5 10. ]


In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[3:])

[20 30 40]
[10 20 30]
[40 50]


In [8]:
# Vectorization
arr = np.array([1, 2, 3, 4])
result_np = arr * 10
print(result_np)

[10 20 30 40]


In [9]:
# Broadcasting
matrix = np.array([10, 20, 30])
result = matrix * 2 #the scalar 2 is stretched to match[2,2,2]
print(result)

[20 40 60]


In [10]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [12]:
print(np.random.rand(3,3))

[[0.38830239 0.25221368 0.05951675]
 [0.6015658  0.78141653 0.04732171]
 [0.41965225 0.82051563 0.61418648]]
